name: fitness
description: A new Flutter fitness app
publish_to: none
version: 0.0.1+1
environment:
  sdk: ">=2.18.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  permission_handler: ^11.3.1

flutter:
  uses-material-design: true


dev_dependencies:
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
